# Site settings
title: Alexandria Mesa
email: mesaac@live.unc.edu
url: https://almesa29.github.io
description: "Library science graduate student at UNC Chapel Hill School of Information and Library Science - interested in academic and special libraries"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Alexandria Mesa
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MesaAlexandria
  - title: facebook
    url:  https://www.facebook.com/alexandria.mesa
  - title: linkedin
    url: https://www.linkedin.com/pub/alexandria-mesa/98/762/859
  - title: github
    url: http://github.com/almesa29
  - title: 
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Durham, NC 27703

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
